language: csharp
sudo: false
env:
  global:
  - PACKAGE_NAME=lassie-${TRAVIS_BUILD_NUMBER}
solution: Lassie.sln
before_script: echo -n "$(cat Lassie/Resources/Version.txt)+${TRAVIS_BUILD_NUMBER} ($(date -u))" > Lassie/Resources/Version.txt
after_success:
- if [[ "$TRAVIS_TAG" != "" ]]; then export PACKAGE_NAME=lassie-${TRAVIS_TAG}; fi
- mkdir dist
- zip -j dist/${PACKAGE_NAME}.zip Lassie/bin/Release/{Lassie.exe,*.dll} LICENSE
deploy:
  provider: s3
  access_key_id: AKIAIJ6RNS2NO5AJFEWA
  secret_access_key:
    secure: cQZRn+JX1QfFMJeQ7odKLytgEaqsnJnjsJKkChOVzc/riULOlYZdRMsdtD9Ma6HzIvMfML+nll0dCibCR4TPH+kzGbQb0eY0a4uTTuH41tlxOjk6GbM/dE5oTKgUt/mjLbBoXeUFLxFCuJu/NWCqJ1l3mcg0JeSvBspqrh2BjJMittQbRBojc7MSD5cxTFmfuIdjNzhoHcqnXXr1xP09zK9wcD3U6iEa+Bwo0c02abwZ0PdjJEr//M6TVlddj13j6UsvEYBwsOETaVRmuzmqQ8YH0Kc4qxqUKn4SJhZFCh4ghRkg4os1uPta7M/H9jiOXQLfdHy36fMycCc3H0+tAkeDFW2u3iFaBEjcp0aNKz4kwQTaeOjeHu2e/oMR937+P2f2Go703wdaizjvF75z3slsfCHbfmMvs5bIcIpTHXEW23GzNDe4JBbi0RaBqk2D9DwdEhR1Sv0ovoy7DQNJboKL2eaT7j8ULkd+Y88ZKR+VVzn0LxHc4qxJrnR9G8uDvBDqHEQeLgbxu+1HXs4En4tmIP9YWpzRppl4TyL5yptcx/Cb3Uj+RKEKg1Bl7QUOfr9MsqfQBT4/wk/QzQEyPw2z1Aq9E4MHdyk2FGk0rMHzfWiQrIdYesBGilaMaVS0ePdHAhxGR38mcH0FkbEH8ZZz8OzG9lvbsyR7pra/Y1Q=
  bucket: erdos
  skip_cleanup: true
  region: eu-west-1
  local_dir: dist
  upload-dir: builds/lassie
  acl: public_read
  on:
    all_branches: true
